export const projects = [
  {
    name: "Study Mate AI",
    date: "2025",
    index: "01",
    description: "RAG-powered study assistant using Next.js and MongoDB Vector Search. Processes documents via Gemini API.",
    tools: ["Next.js", "MongoDB", "Gemini", "Express"],
    link: "https://github.com/SmonFtwi/studyMateAI",
    image: "/studymageDash.png",
    accent: "#6ee7b7",
  },
  {
    name: "Smart ATS",
    date: "2024",
    index: "02",
    description: "AI-driven resume analyzer comparing profiles with job descriptions using LLMs.",
    tools: ["Streamlit", "Gemini", "Python"],
    link: "https://github.com/SmonFtwi/Resume-ATSS-system",
    image: "/ats.png",
    accent: "#93c5fd",
  },
  {
    name: "Movie Explorer",
    date: "2023",
    index: "03",
    description: "High-performance interface for exploring TMDB catalog with curated watchlists.",
    tools: ["React", "Tailwind", "Vite"],
    link: "https://github.com/SmonFtwi/movie-app",
    image: "/movieApp.png",
    accent: "#fcd34d",
  },
  {
    name: "AI Text Summarizer",
    date: "2023",
    index: "04",
    description: "Pegasus-based summarizer producing concise conversation recaps for chat datasets.",
    tools: ["PyTorch", "Streamlit", "Transformers"],
    link: "https://github.com/SmonFtwi/TextSummarizer-pegasus-model",
    image: "/chatsum.png",
    accent: "#f9a8d4",
  },
  {
    name: "Network Automation",
    date: "2023",
    index: "05",
    description: "Automated SD-WAN provisioning with VLAN and IPsec for enterprise deployments.",
    tools: ["GNS3", "SD-WAN", "IPSec"],
    link: "https://docs.google.com/document/d/1MaIAKcjev5WY3DqXKLQSInHk1U93NQWu/edit",
    image: "/Picture1.png",
    accent: "#c4b5fd",
  },
];

export type Project = typeof projects[0];
